#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

start_service() {
    logger -p daemon.info -t "u3_service" "Starting u3 camera service"
    
    procd_open_instance
    procd_set_param command /bin/sh -c 'while true; do
        /bin/u3.sh
        
        # Load interval from .env file
        if [ -f "/root/.env" ]; then
            . /root/.env
            INTERVAL="$UPLOAD_INTERVAL"
        fi
        
        # Set default if empty or invalid
        case "$INTERVAL" in
            '"'"''"'"'|*[!0-9]*) INTERVAL=60 ;;
            *)
                if [ "$INTERVAL" -lt 5 ]; then INTERVAL=5; fi
                if [ "$INTERVAL" -gt 3600 ]; then INTERVAL=3600; fi
                ;;
        esac
        
        logger -p daemon.debug -t "u3_service" "Sleeping for $INTERVAL seconds"
        echo "Sleeping for $INTERVAL seconds"
        sleep $INTERVAL
    done'
    procd_set_param respawn 4 20 20
    procd_close_instance
    
    logger -p daemon.info -t "u3_service" "u3 camera service started"
}

stop_service() {
    logger -p daemon.info -t "u3_service" "Stopping u3 camera service"
    service_stop /bin/sh
}

service_triggers() {
    procd_add_reload_trigger "camera"
}
